package ledger

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeProjectFile(t *testing.T, root, path, content string) {
	t.Helper()
	path = filepath.Join(root, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func goProject(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	writeProjectFile(t, root, ConfigFilename, "version: 1\nservices:\n  - name: reports\n    owner: reporting-team\n    source: services/reports\n")
	writeProjectFile(t, root, "services/reports/schema.sql", "CREATE TABLE public.reports (id INTEGER);")
	writeProjectFile(t, root, "services/reports/http.go", `package reports
import "net/http"
func Register(mux *http.ServeMux) { mux.HandleFunc("GET /reports", listReports) }
func listReports(w http.ResponseWriter, r *http.Request) { loadReports() }
`)
	writeProjectFile(t, root, "services/reports/store.go", `package reports
import "database/sql"
var db *sql.DB
const reportSQL = "SELECT id FROM public.reports"
func loadReports() { db.Query(reportSQL) }
`)
	return root
}

func TestGoScanPathOwnershipAndReplacement(t *testing.T) {
	root := goProject(t)
	db := newTestDB(t)
	first, err := Scan(db, root)
	if err != nil {
		t.Fatal(err)
	}
	if first.Stats.Functions != 3 || first.Stats.Routes != 1 || first.Stats.Queries != 1 {
		t.Fatalf("source assets missing: %+v", first)
	}
	var routeID, tableID int64
	if err := db.QueryRow(`SELECT id FROM assets WHERE kind = 'route'`).Scan(&routeID); err != nil {
		t.Fatal(err)
	}
	if err := db.QueryRow(`SELECT id FROM assets WHERE kind = 'table'`).Scan(&tableID); err != nil {
		t.Fatal(err)
	}
	report, err := FindPath(db, fmt.Sprintf("id:%d", routeID), fmt.Sprintf("id:%d", tableID))
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Steps) != 4 {
		t.Fatalf("expected route -> handler -> helper -> query -> table: %+v", report)
	}
	for _, step := range report.Steps {
		if step.Origin != "source-derived" || len(step.Evidence) == 0 || len(step.Owners) != 1 || len(step.Teams) != 1 || step.Teams[0] != "reporting-team" {
			t.Fatalf("missing source provenance or ownership: %+v", step)
		}
	}
	if _, err := Build(db); err != nil {
		t.Fatal(err)
	}
	second, err := Scan(db, root)
	if err != nil || first.Stats != second.Stats {
		t.Fatalf("non-idempotent scan: %+v %+v %v", first, second, err)
	}
	if metadata(db, "last_build_at") != "" {
		t.Fatal("rescan did not invalidate build")
	}
	if err := os.Rename(filepath.Join(root, "services/reports/store.go"), filepath.Join(root, "services/reports/data.go")); err != nil {
		t.Fatal(err)
	}
	if Verification(db).Valid {
		t.Fatal("rename did not invalidate provenance")
	}
	if _, err := Scan(db, root); err != nil {
		t.Fatal(err)
	}
	var obsolete int
	if err := db.QueryRow(`SELECT COUNT(*) FROM sources WHERE path LIKE '%store.go'`).Scan(&obsolete); err != nil || obsolete != 0 {
		t.Fatalf("obsolete source survived: %d %v", obsolete, err)
	}
	for _, name := range []string{"http.go", "data.go"} {
		if err := os.Remove(filepath.Join(root, "services/reports", name)); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := Scan(db, root); err != nil {
		t.Fatal(err)
	}
	if err := db.QueryRow(`SELECT COUNT(*) FROM assets WHERE kind IN ('function','route','query')`).Scan(&obsolete); err != nil || obsolete != 0 {
		t.Fatalf("obsolete code graph survived: %d %v", obsolete, err)
	}
	if err := Verify(db); err != nil {
		t.Fatal(err)
	}
}

func TestScanFailureIsTransactionalAndAddedFilesAreStale(t *testing.T) {
	root := goProject(t)
	db := newTestDB(t)
	if _, err := Scan(db, root); err != nil {
		t.Fatal(err)
	}
	before, err := Summary(db)
	if err != nil {
		t.Fatal(err)
	}
	writeProjectFile(t, root, "services/reports/new.go", "package reports\nfunc broken(")
	if Verification(db).Valid {
		t.Fatal("new input not detected")
	}
	if _, err := Build(db); err == nil {
		t.Fatal("build accepted stale source inventory")
	}
	if _, err := Scan(db, root); err == nil {
		t.Fatal("malformed Go scan succeeded")
	}
	after, err := Summary(db)
	if err != nil || before.Assets != after.Assets || before.LastScanAt != after.LastScanAt {
		t.Fatalf("failed scan changed ledger: before=%+v after=%+v err=%v", before, after, err)
	}
}

func TestSourceExclusionsAndSymlinkIntegrity(t *testing.T) {
	root := goProject(t)
	for _, path := range []string{".git/a.go", "vendor/a.go", "node_modules/a.go", ".env", "credentials.json", "services/reports/a_test.go"} {
		writeProjectFile(t, root, path, "not valid source")
	}
	writeProjectFile(t, root, "services/reports/generated.go", "// Code generated by synthetic fixture. DO NOT EDIT.\npackage reports\nfunc Generated() {}\n")
	outside := t.TempDir()
	writeProjectFile(t, outside, "escape.go", "package escape\nfunc Outside() {}")
	if err := os.Symlink(filepath.Join(outside, "escape.go"), filepath.Join(root, "escape.go")); err != nil {
		t.Fatal(err)
	}
	db := newTestDB(t)
	scan, err := Scan(db, root)
	if err != nil || scan.Stats.Functions != 3 {
		t.Fatalf("excluded source ingested: %+v %v", scan, err)
	}
	for _, name := range []string{"Generated", "Outside"} {
		if _, err := findAsset(db, name); err == nil {
			t.Fatalf("excluded function %q found", name)
		}
	}
	path := filepath.Join(root, "services/reports/http.go")
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	writeProjectFile(t, outside, "same.go", string(content))
	if err := os.Remove(path); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(outside, "same.go"), path); err != nil {
		t.Fatal(err)
	}
	if Verification(db).Valid {
		t.Fatal("same-hash symlink escape accepted")
	}
}

func TestSQLScopeDoesNotGuessAcrossServices(t *testing.T) {
	for _, scenario := range []string{"other-service", "ambiguous", "unmapped", "unknown-search-path"} {
		t.Run(scenario, func(t *testing.T) {
			root := goProject(t)
			switch scenario {
			case "other-service":
				if err := os.Remove(filepath.Join(root, "services/reports/schema.sql")); err != nil {
					t.Fatal(err)
				}
				writeProjectFile(t, root, "services/unrelated/schema.sql", "CREATE TABLE public.reports (id INTEGER);")
			case "ambiguous":
				writeProjectFile(t, root, "services/reports/second.sql", "CREATE TABLE public.reports (id INTEGER);")
			case "unmapped":
				writeProjectFile(t, root, ConfigFilename, "version: 1\nservices: []\n")
			case "unknown-search-path":
				writeProjectFile(t, root, "services/reports/store.go", `package reports
import "database/sql"
var db *sql.DB
func loadReports() { db.Query("SELECT id FROM reports") }
`)
			}
			db := newTestDB(t)
			result, err := Scan(db, root)
			if err != nil {
				t.Fatal(err)
			}
			var count int
			if err := db.QueryRow(`SELECT COUNT(*) FROM relationships WHERE relationship_type IN ('reads_table','writes_table')`).Scan(&count); err != nil || count != 0 {
				t.Fatalf("unjustified SQL relation: %d %v", count, err)
			}
			if result.Stats.Gaps == 0 {
				t.Fatal("unresolved SQL scope missing diagnostic")
			}
			var text bytes.Buffer
			if err := WriteSummary(db, &text, "text"); err != nil || !strings.Contains(text.String(), "Extraction gaps") {
				t.Fatalf("missing text diagnostics: %s %v", text.String(), err)
			}
		})
	}
}

func TestServiceRootSymlinkRejected(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	if err := os.Symlink(outside, filepath.Join(root, "service")); err != nil {
		t.Fatal(err)
	}
	writeProjectFile(t, root, ConfigFilename, "version: 1\nservices:\n  - name: escape\n    owner: team\n    source: service\n")
	if _, err := Scan(newTestDB(t), root); err == nil {
		t.Fatal("symlink service root accepted")
	}
}

func TestProjectRootSymlinkCannotClearLedger(t *testing.T) {
	root := goProject(t)
	db := newTestDB(t)
	before, err := Scan(db, root)
	if err != nil {
		t.Fatal(err)
	}
	linked := filepath.Join(t.TempDir(), "linked")
	if err := os.Symlink(root, linked); err != nil {
		t.Fatal(err)
	}
	if _, err := Scan(db, linked); err == nil {
		t.Fatal("symlink project root accepted")
	}
	var functions int
	if err := db.QueryRow(`SELECT COUNT(*) FROM assets WHERE kind = 'function'`).Scan(&functions); err != nil || functions != before.Stats.Functions {
		t.Fatalf("failed symlink scan changed graph: %d %v", functions, err)
	}
}

func TestSQLTextCannotFabricateDDLTargets(t *testing.T) {
	root := goProject(t)
	writeProjectFile(t, root, "services/reports/schema.sql", `
SELECT 'CREATE TABLE public.reports (id INTEGER);';
SELECT 'x; CREATE TABLE public.reports (id INTEGER);';
-- CREATE TABLE public.reports (id INTEGER);
/* nested /* comment */ CREATE TABLE public.reports (id INTEGER); */
DO $body$ BEGIN; CREATE TABLE public.reports (id INTEGER); END $body$;
CREATE TABLE /*!50000 actual_table AS */ public.reports (id INTEGER);
CREATE TABLE /*M! actual_table AS */ public.reports (id INTEGER);
CREATE TABLE /*m! actual_table AS */ public.reports (id INTEGER);
CREATE TABLE "public.reports" (id INTEGER);
CREATE TABLE actual_table (id INTEGER);
`)
	db := newTestDB(t)
	result, err := Scan(db, root)
	if err != nil {
		t.Fatal(err)
	}
	if result.Stats.Tables != 1 {
		t.Fatalf("SQL text manufactured tables: %+v", result)
	}
	var count int
	if err := db.QueryRow(`SELECT COUNT(*) FROM relationships WHERE relationship_type = 'reads_table'`).Scan(&count); err != nil || count != 0 {
		t.Fatalf("query linked to fabricated DDL: %d %v", count, err)
	}
}
